# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # Setup key
    - name: Set eu 
      run: set -eu
    - name: Create dir
      run: mkdir "$HOME/.ssh"
    - name: Create .ssh
      run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
    - name: Chmod
      run: chmod 600 "$HOME/.ssh/key"
    # Deploy
    - name: Deploy
      run: cd ./ && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@185.206.212.246:/root/MasterskayaPartyBot/ && npm i
